### ISSUE TITLE
Allow to set maxInflight or pass MqttClient provider function to the Homie

### ISSUE THREAD

**Issue by OlegAndreych** [dschanoeh/homie-java#9]
I'm facing with the `Too many publishes in progress (32202)` error using the default configuration of a `MqttClient` in `homie-java`.  
I think either way would work. What's your opinion?

**Comment by dschanoeh** [comment]
Hi,
with 76bbc0301c797279567d34fd2b47f153e1c8dd47, we've already introduced a simple scaling of maxInFlight. I guess that's not working for your case, though. May I ask what your setup is? How many topics are you publishing and how frequently? I'm surprised that we'd have to work around issues like this here.
I've just looked at [the MQTT client library releases](https://github.com/eclipse/paho.mqtt.java/releases) and it looks like version 1.2.5 has been published and in the meantime a few bugs regarding maxInFlight were fixed. Do you still see the issue when manually rebuilding pi-homie with org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5?

**Comment by OlegAndreych** [comment]
My setup has about 60 topics. The frequency of publishing isn't great, but I have bursts when all topics are updated at once.
I've changed the scaling ratio in `maxInFlight` to the 5 (instead of 2) but not tried to fine-tune it. Maybe 3 would be sufficient.
I'll try to revert to the ratio of 2 and update the MQTT client.

**Comment by OlegAndreych** [comment]
A client update didn' help.

**Comment by dschanoeh** [comment]
Okay, too bad.
Regarding a fix in homie-java, I'm thinking overloading the Homie constructor and giving the option to pass your own MqttConnectOptions instance. Would that work or are there disadvantages to this?

**Comment by OlegAndreych** [comment]
I think that would work.

**Comment by dschanoeh** [comment]
With the current HEAD (0.1.1-SNAPSHOT), you should be able to pass your own options. Can you give feedback if that works?

**Comment by OlegAndreych** [comment]
I cannot publish artifact to the local maven repo when at HEAD.
I'm far from mastering Gradle, but should we set `jar` as the `archiveClassifier` for the `shadowJar`?

Command to perform local publishing I use is `./gradlew clean build publishToMavenLocal -x test`.

**Comment by OlegAndreych** [comment]
Aha, seems like `archiveVersion = project.getVersion()` call in the `shadowJar` makes Gradle to generate artifact named as `homie-java-unspecified.jar`.
In case I write the `archiveVersion` explicitly everything publishes fine and the content of a jar is like it's shadowed properly (Paho classes are here).

**Comment by OlegAndreych** [comment]
I think moving `project.version` definition higher than the `shadowJar` makes `project.getVersion()` work properly.

**Comment by OlegAndreych** [comment]
Other than that, everything worked like a charm. Thank you!
